spring.application.name=auth-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=merchantharmony
spring.datasource.password=merchantharmony
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.com.merchantharmony=INFO
