spring.application.name=engagement-service
server.port=8082

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5434/engagement_db}
spring.datasource.username=${DB_USERNAME:merchantharmony}
spring.datasource.password=${DB_PASSWORD:merchantharmony}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.com.merchantharmony=INFO
